In [1]:
import pandas as pd
import numpy as np

In [2]:
la_crimes=pd.read_csv('F:/LA_crime.csv')

In [3]:
la_crimes.rename(columns={'AREA ': 'AREA'}, inplace = True)
la_crimes

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2114694,190608903,03/28/2019 12:00:00 AM,03/28/2019 12:00:00 AM,400,6,Hollywood,644,1,648,ARSON,...,IC,Invest Cont,648.0,NaN,NaN,NaN,1400 N LA BREA AV,NaN,34.0962,-118.3490
2114695,190715222,08/15/2019 12:00:00 AM,08/14/2019 12:00:00 AM,1810,7,Wilshire,701,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),...,IC,Invest Cont,331.0,NaN,NaN,NaN,WILLOUGHBY AV,ORLANDO AV,34.0871,-118.3732
2114696,192004409,01/06/2019 12:00:00 AM,01/06/2019 12:00:00 AM,2100,20,Olympic,2029,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,IC,Invest Cont,930.0,NaN,NaN,NaN,6TH,VIRGIL,34.0637,-118.2870
2114697,191716777,10/17/2019 12:00:00 AM,10/16/2019 12:00:00 AM,1800,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,17200 NAPA ST,NaN,34.2266,-118.5085
2114698,190805435,02/01/2019 12:00:00 AM,02/01/2019 12:00:00 AM,1615,8,West LA,852,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,1700 BARRY AV,NaN,34.0420,-118.4531

In [38]:
#DR_NO column
#We see that the column DR_NO is a unique code for each row, that means each crime reported has a different code

In [4]:
la_crimes['DR_NO'].value_counts()

1307355      1
160510095    1
161429600    1
161422464    1
160120969    1
            ..
132111278    1
140100761    1
131210333    1
130611578    1
190805435    1
Name: DR_NO, Length: 2114699, dtype: int64

In [5]:
#Date Rptd and DATE OCC columns
#We see that all the dates have the time of 12:00:00 AM

In [6]:
la_crimes['Date Rptd'].str[-8:].value_counts() #selecting only the time and getting the different values of it

00:00 AM    2114699
Name: Date Rptd, dtype: int64

In [7]:
la_crimes['DATE OCC'].str[-8:].value_counts() #selecting only the time and getting the different values of it

00:00 AM    2114699
Name: DATE OCC, dtype: int64

In [8]:
#As result, we can delete the data of the time because it does not give additional information to us

In [9]:
la_crimes['Date Rptd'] = la_crimes['Date Rptd'].str[:10] #only keeping the data of the date without the time

In [10]:
la_crimes['DATE OCC'] = la_crimes['DATE OCC'].str[:10] #only keeping the data

In [11]:
#Now we are going to bring the date format to the appropriate one for databases: YYYY-MM-DD

In [12]:
la_crimes['Date Rptd'] = pd.to_datetime(la_crimes['Date Rptd'])
la_crimes['DATE OCC'] = pd.to_datetime(la_crimes['DATE OCC'])
la_crimes['Date Rptd'].sample(5)

381155   2012-01-11
515149   2012-10-17
207280   2013-09-11
953792   2014-03-10
240978   2011-11-27
Name: Date Rptd, dtype: datetime64[ns]

In [13]:
#TIME OCC column

In [14]:
la_crimes['TIME OCC'] = la_crimes['TIME OCC'].astype(str)

In [15]:
la_crimes['TIME OCC']= '00'+la_crimes['TIME OCC']

In [16]:
la_crimes['TIME OCC']

0          001350
1            0045
2          001515
3           00150
4          002100
            ...
2114694     00400
2114695    001810
2114696    002100
2114697    001800
2114698    001615
Name: TIME OCC, Length: 2114699, dtype: object

In [17]:
la_crimes['TIME OCC'] = la_crimes['TIME OCC'].str[-4:-2] + ':' +la_crimes['TIME OCC'].str[-2:]

In [18]:
la_crimes['DATE OCC'] = la_crimes['DATE OCC'].astype(str) +' ' + la_crimes['TIME OCC']
la_crimes['DATE OCC'] = pd.to_datetime(la_crimes['DATE OCC'])

In [19]:
la_crimes = la_crimes.drop(['TIME OCC'], axis=1)

In [20]:
la_crimes['DATE OCC']

0         2010-02-20 13:50:00
1         2010-09-12 00:45:00
2         2010-08-09 15:15:00
3         2010-01-05 01:50:00
4         2010-01-02 21:00:00
                  ...
2114694   2019-03-28 04:00:00
2114695   2019-08-14 18:10:00
2114696   2019-01-06 21:00:00
2114697   2019-10-16 18:00:00
2114698   2019-02-01 16:15:00
Name: DATE OCC, Length: 2114699, dtype: datetime64[ns]

In [21]:
#Mocodes column
#We see that some crime reports have null values for the column of Mocodes

In [22]:
la_crimes.loc[la_crimes['Mocodes'].isna()]

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
15,100100535,2010-01-17,2010-01-16 17:35:00,1,Central,185,2,946,OTHER MISCELLANEOUS CRIME,NaN,...,IC,Invest Cont,946.0,999.0,NaN,NaN,300 E OLYMPIC BL,NaN,34.0389,-118.2550
28,100100578,2010-02-05,2010-02-03 12:55:00,1,Central,185,2,946,OTHER MISCELLANEOUS CRIME,NaN,...,IC,Invest Cont,946.0,999.0,NaN,NaN,1200 MAPLE AV,NaN,34.0357,-118.2563
51,100100654,2010-02-27,2010-02-27 19:55:00,1,Central,174,2,946,OTHER MISCELLANEOUS CRIME,NaN,...,AA,Adult Arrest,946.0,NaN,NaN,NaN,W 7TH ST,S SPRING ST,34.0445,-118.2523
79,100100730,2010-03-23,2010-03-20 12:15:00,1,Central,111,2,647,THROWING OBJECT AT MOVING VEHICLE,NaN,...,IC,Invest Cont,647.0,NaN,NaN,NaN,CESAR E CHAVEZ,FIGUEROA ST,34.0627,-118.2463
102,100100786,2010-04-08,2010-04-08 02:20:00,1,Central,161,1,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,520.0,NaN,NaN,FRANCISCO ST,8TH ST,34.0481,-118.2633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2114663,190417846,2019-12-11,2019-12-06 18:00:00,4,Hollenbeck,423,1,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,1100 N MISSION RD,NaN,34.0651,-118.2116
2114670,191710450,2019-05-25,2019-05-25 06:30:00,17,Devonshire,1761,1,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,9200 ETON AV,NaN,34.2376,-118.5947
2114683,191816545,2019-07-22,2019-07-17 20:30:00,18,Southeast,1836,2,922,CHILD STEALING,NaN,...,AO,Adult Other,922.0,NaN,NaN,NaN,10400 FIRTH AV,NaN,33.9424,-118.2477
2114691,191307168,2019-02-28,2019-02-28 07:00:00,13,Newton,1394,1,510,VEHICLE - STOLEN,NaN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,100 E 67TH ST,NaN,33.9788,-118.2739
2114697,191716777,2019-10-17,2019-10-16 18:00:00,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),NaN,...,IC,Invest Cont,420.0,NaN,NaN,NaN,17200 NAPA ST,NaN,34.2266,-118.5085

In [23]:
indexes_null_mo = la_crimes.loc[la_crimes ['Mocodes'].isna()].index
la_crimes.loc[indexes_null_mo,'Mocodes'] = 'unknown'

In [24]:
#Vict Age column
#Now we are going to fix the column Vict Age that don't make any sense
#Specifically we are going to change all negative age numbers to 0 which we consider missing value.

In [25]:
la_crimes['Vict Age'].value_counts()

 0      369886
 25      48101
 26      47469
 27      47011
 24      46739
         ...
-7          15
-8           7
-9           4
 114         1
 118         1
Name: Vict Age, Length: 110, dtype: int64

In [26]:
indexes_neg_age = la_crimes.loc[la_crimes['Vict Age'] < 0]['Vict Age'].index #finding the indexes of negative ages
la_crimes.loc[indexes_neg_age,'Vict Age'] = 0

In [27]:
#Vict Sex column
#Now we fix the column Vict Sex which is the victim's sex
#According to the description the values are: F - Female, M - Male, X - Unknown

In [28]:
la_crimes['Vict Sex'].value_counts()

M    974309
F    888499
X     55129
H        73
N        17
-         1
Name: Vict Sex, dtype: int64

In [29]:
indexes_wrong_sex = la_crimes.loc[(la_crimes['Vict Sex'] != 'M') & (la_crimes['Vict Sex'] != 'F')].index
la_crimes.loc[indexes_wrong_sex,'Vict Sex'] = 'X'

In [30]:
#Vict Descent column

In [31]:
print("The reported crimes with Nan (null) values for the column Vict Descent are:")
len(la_crimes.loc[la_crimes['Vict Descent'].isna()])

The reported crimes with Nan (null) values for the column Vict Descent are:

196718

In [33]:
la_crimes['Vict Descent'].value_counts()

H    725348
W    510158
B    335102
O    202969
X     78147
A     51109
K      9141
F      2553
C      1061
I       945
J       418
P       343
V       201
U       190
Z       136
G        85
S        31
D        23
L        18
-         3
Name: Vict Descent, dtype: int64

In [34]:
indexes_wrong_decent = la_crimes.loc[(la_crimes['Vict Descent'] == '-') | (la_crimes['Vict Descent'].isna())].index
la_crimes.loc[indexes_wrong_decent,'Vict Descent'] = 'X'

In [35]:
#Premis Cd and Premis Desc columns

In [36]:
la_crimes.loc[la_crimes['Premis Cd'].isna()]

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
6590,100121447,2010-12-12,2010-12-12 11:50:00,1,Central,185,1,110,CRIMINAL HOMICIDE,unknown,...,AA,Adult Arrest,110.0,NaN,NaN,NaN,200 W OLYMPIC BL,NaN,34.0409,-118.2574
32148,100913648,2010-06-21,2010-06-20 14:35:00,9,Van Nuys,915,1,510,VEHICLE - STOLEN,unknown,...,IC,Invest Cont,510.0,NaN,NaN,NaN,7000 VAN NUYS BL,NaN,34.1976,-118.4487
67340,100816222,2010-09-03,2010-04-16 00:01:00,8,West LA,803,2,813,CHILD ANNOYING (17YRS & UNDER),unknown,...,IC,Invest Cont,813.0,NaN,NaN,NaN,2000 MANDAVILLE C,NaN,34.0949,-118.5111
68276,100818222,2010-11-18,2010-10-16 16:00:00,8,West LA,811,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,unknown,...,IC,Invest Cont,812.0,NaN,NaN,NaN,1100 LAS PULGAS RD,NaN,34.0528,-118.5393
71523,100908076,2010-03-16,2010-03-15 22:05:00,15,N Hollywood,1547,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,IC,Invest Cont,420.0,NaN,NaN,NaN,BECK,CHANDLER,34.1687,-118.3834
85649,101017796,2010-09-21,2010-09-08 17:20:00,10,West Valley,1067,2,813,CHILD ANNOYING (17YRS & UNDER),unknown,...,AO,Adult Other,813.0,NaN,NaN,NaN,5400 LOUISE AV,NaN,34.1694,-118.5098
92668,101114489,2010-06-18,2010-06-18 19:10:00,11,Northeast,1178,1,820,ORAL COPULATION,unknown,...,IC,Invest Cont,820.0,NaN,NaN,NaN,CYPRESS AV,FIGUEROA,34.0864,-118.2190
102768,101214269,2010-05-13,2010-05-12 18:00:00,12,77th Street,1242,1,235,CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT,unknown,...,IC,Invest Cont,235.0,NaN,NaN,NaN,6200 3RD AV,NaN,33.9837,-118.3206
107695,101223939,2010-09-17,2010-06-01 12:00:00,12,77th Street,1213,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,unknown,...,IC,Invest Cont,812.0,NaN,NaN,NaN,1700 W 52ND ST,NaN,33.9951,-118.3068
124293,101410405,2010-04-12,2010-04-11 23:20:00,14,Pacific,1494,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,AA,Adult Arrest,420.0,NaN,NaN,NaN,300 WORLD WY,NaN,33.9440,-118.4073
181888,101926208,2010-12-07,2010-12-07 13:30:00,19,Mission,1963,1,510,VEHICLE - STOLEN,unknown,...,IC,Invest Cont,510.0,NaN,NaN,NaN,14500 VAN NUYS BL,NaN,34.2471,-118.4482
223337,111800860,2011-04-25,2011-04-24 20:30:00,18,Southeast,1837,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",unknown,...,AA,Adult Arrest,230.0,NaN,NaN,NaN,1800 E 108TH ST,NaN,33.9379,-118.2407
236205,111614486,2011-08-07,2011-08-07 12:20:00,16,Foothill,1676,2,922,CHILD STEALING,unknown,...,AA,Adult Arrest,922.0,978.0,986.0,NaN,10700 NEW HAVEN ST,NaN,34.2265,-118.3644
244481,110104233,2011-01-06,2011-01-02 16:19:00,1,Central,156,1,110,CRIMINAL HOMICIDE,unknown,...,IC,Invest Cont,110.0,NaN,NaN,NaN,500 S SAN PEDRO ST,NaN,34.0442,-118.2439
246857,111820353,2011-10-21,2011-09-13 10:02:00,18,Southeast,1804,2,813,CHILD ANNOYING (17YRS & UNDER),unknown,...,IC,Invest Cont,813.0,NaN,NaN,NaN,700 E 87TH ST,NaN,33.9593,-118.2630
256518,111412807,2011-04-16,2011-04-16 16:00:00,14,Pacific,1488,2,753,DISCHARGE FIREARMS/SHOTS FIRED,unknown,...,IC,Invest Cont,521.0,753.0,NaN,NaN,5800 96TH ST,NaN,33.9495,-118.3835
289994,112020223,2011-10-20,2011-10-13 20:00:00,20,Olympic,2044,1,235,CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT,unknown,...,IC,Invest Cont,235.0,NaN,NaN,NaN,800 S HARVARD BL,NaN,34.0577,-118.3042
326213,110616246,2011-06-20,2011-06-20 04:10:00,6,Hollywood,646,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,unknown,...,IC,Invest Cont,626.0,NaN,NaN,NaN,WILCOX,HOLLYWOOD BL,34.1016,-118.3310
327485,111400001,2011-02-11,2011-02-10 20:45:00,14,Pacific,1494,2,649,DOCUMENT FORGERY / STOLEN FELONY,unknown,...,IC,Invest Cont,649.0,NaN,NaN,NaN,300 WORLD WY,NaN,33.9440,-118.4073
390593,111428080,2011-10-05,2011-10-05 14:05:00,14,Pacific,1494,2,649,DOCUMENT FORGERY / STOLEN FELONY,unknown,...,IC,Invest Cont,649.0,NaN,NaN,NaN,200 WORLD WY,NaN,33.9449,-118.4059
441754,121815392,2012-08-06,2012-08-04 17:30:00,18,Southeast,1832,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,unknown,...,IC,Invest Cont,812.0,NaN,NaN,NaN,10700 S MAIN ST,NaN,33.9392,-118.2739
530688,120706377,2012-02-23,2012-02-23 17:30:00,7,Wilshire,788,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",unknown,...,IC,Invest Cont,230.0,NaN,NaN,NaN,4000 W WASHINGTON BL,NaN,34.0399,-118.3271
563146,120619583,2012-07-16,2012-06-16 12:00:00,6,Hollywood,644,2,922,CHILD STEALING,unknown,...,CC,UNK,922.0,986.0,NaN,NaN,1300 N VISTA ST,NaN,34.0944,-118.3517
570068,121412515,2012-05-03,2012-05-03 15:20:00,14,Pacific,1473,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0344,...,IC,Invest Cont,440.0,NaN,NaN,NaN,00,NaN,33.9588,-118.4374
603839,121801492,2012-11-22,2012-11-21 23:00:00,18,Southeast,1805,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",unknown,...,IC,Invest Cont,230.0,NaN,NaN,NaN,SAN PEDRO,91ST ST,33.9538,-118.2695
684026,131416539,2013-06-24,2013-06-24 01:05:00,14,Pacific,1494,2,649,DOCUMENT FORGERY / STOLEN FELONY,unknown,...,AA,Adult Arrest,649.0,998.0,NaN,NaN,SEPULVEDA BL,IMPERIAL,33.9309,-118.3961
691500,131706326,2013-02-20,2013-02-20 17:50:00,17,Devonshire,1747,2,666,"BUNCO, ATTEMPT",unknown,...,AA,Adult Arrest,666.0,NaN,NaN,NaN,BALBOA BL,KINGSBURY ST,34.2636,-118.5023
794923,131511839,2013-05-29,2013-05-29 08:20:00,15,N Hollywood,1516,2,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,unknown,...,AA,Adult Arrest,627.0,NaN,NaN,NaN,6600 BECK AV,NaN,34.1903,-118.3834
811749,151704507,2015-01-13,2014-01-13 13:30:00,17,Devonshire,1793,1,440,THEFT PLAIN - PETTY ($950 & UNDER),unknown,...,IC,Invest Cont,440.0,NaN,NaN,NaN,8700 VANALDEN AV,NaN,34.2283,-118.5492
827479,141817287,2014-09-17,2014-09-16 08:11:00,18,Southeast,1802,1,110,CRIMINAL HOMICIDE,unknown,...,IC,Invest Cont,110.0,NaN,NaN,NaN,9000 S MAIN ST,NaN,33.9546,-118.2739
878694,140511089,2014-06-21,2014-06-21 14:35:00,5,Harbor,513,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0104 0344 0378 1309,...,IC,Invest Cont,440.0,NaN,NaN,NaN,00,NaN,0.0000,0.0000
888806,142111719,2014-06-21,2014-06-21 21:12:00,21,Topanga,2105,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),unknown,...,IC,Invest Cont,442.0,NaN,NaN,NaN,00,NaN,0.0000,0.0000
915055,140913407,2014-07-18,2014-07-18 10:00:00,9,Van Nuys,915,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,unknown,...,AO,Adult Other,930.0,NaN,NaN,NaN,00,NaN,0.0000,0.0000
950356,141012475,2014-07-19,2014-07-19 20:40:00,10,West Valley,1077,1,330,BURGLARY FROM VEHICLE,0344 0377 1609 1420,...,IC,Invest Cont,330.0,NaN,NaN,NaN,00,NaN,0.0000,0.0000
957521,141811155,2014-05-24,2014-05-22 18:50:00,18,Southeast,1846,2,624,BATTERY - SIMPLE ASSAULT,unknown,...,IC,Invest Cont,624.0,NaN,NaN,NaN,1400 E 112TH ST,NaN,33.9326,-118.2502
967557,150206736,2015-02-20,2014-11-18 23:00:00,2,Rampart,246,1,815,SEXUAL PENETRATION W/FOREIGN OBJECT,unknown,...,IC,Invest Cont,815.0,NaN,NaN,NaN,500 S WESTLAKE AV,NaN,34.0598,-118.2731
967979,141000807,2014-07-19,2014-07-19 10:30:00,10,West Valley,1027,1,310,BURGLARY,0344 1606 1414,...,IC,Invest Cont,310.0,NaN,NaN,NaN,00,NaN,0.0000,0.0000
977511,142111721,2014-06-22,2014-06-21 22:00:00,21,Topanga,2145,1,510,VEHICLE - STOLEN,unknown,...,IC,Invest Cont,510.0,NaN,NaN,NaN,00,NaN,0.0000,0.0000
987563,141508150,2014-03-23,2014-03-23 23:30:00,15,N Hollywood,1525,1,235,CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT,unknown,...,AO,Adult Other,235.0,NaN,NaN,NaN,5600 COLFAX AV,NaN,34.1722,-118.3877
1294312,161112881,2016-07-04,2016-07-04 00:05:00,11,Northeast,1117,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",unknown,...,IC,Invest Cont,230.0,NaN,NaN,NaN,CAMPUS RD,RIDGEVIEW,34.1299,-118.2120
1364942,170906911,2017-02-27,2016-11-24 17:00:00,9,Van Nuys,923,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,unknown,...,AO,Adult Other,812.0,NaN,NaN,NaN,14800 LEMAY ST,NaN,34.1920,-118.4555
1417580,161400604,2016-04-17,2016-04-14 12:00:00,10,West Valley,1027,2,237,CHILD NEGLECT (SEE 300 W.I.C.),unknown,...,AA,Adult Arrest,237.0,NaN,NaN,NaN,6900 ALDEA AV,NaN,34.1957,-118.5084
1452779,171704122,2017-01-03,2017-01-02 18:00:00,17,Devonshire,1752,1,210,ROBBERY,unknown,...,IC,Invest Cont,210.0,NaN,NaN,NaN,9900 DE SOTO AV,NaN,34.2500,-118.5886
1465775,171804995,2017-01-18,2017-01-18 18:45:00,18,Southeast,1821,2,946,OTHER MISCELLANEOUS CRIME,unknown,...,AA,Adult Arrest,521.0,946.0,NaN,NaN,104TH ST,VERMONT AV,33.9423,-118.2916
1511359,171804978,2017-01-18,2017-01-18 14:48:00,18,Southeast,1846,2,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,unknown,...,AO,Adult Other,627.0,NaN,NaN,NaN,1200 E 112TH ST,NaN,33.9331,-118.2542
1667060,170918599,2017-10-01,2017-09-30 19:00:00,9,Van Nuys,989,1,815,SEXUAL PENETRATION W/FOREIGN OBJECT,unknown,...,AO,Adult Other,815.0,NaN,NaN,NaN,4200 SUNNYSLOPE AV,NaN,34.1473,-118.4270
1814056,180804421,2018-01-11,2018-01-10 23:00:00,8,West LA,881,2,946,OTHER MISCELLANEOUS CRIME,unknown,...,IC,Invest Cont,946.0,NaN,NaN,NaN,2200 FEDERAL AV,NaN,34.0341,-118.4525
1818531,181719036,2018-11-17,2018-09-11 12:30:00,17,Devonshire,1778,2,624,BATTERY - SIMPLE ASSAULT,unknown,...,AA,Adult Arrest,624.0,NaN,NaN,NaN,16100 PLUMMER ST,NaN,34.2465,-118.4806
1947458,191307542,2019-03-06,2019-03-06 16:45:00,13,Newton,1307,1,510,VEHICLE - STOLEN,unknown,...,NaN,UNK,510.0,NaN,NaN,NaN,STANFORD,8TH ST,34.0365,-118.2468
1968622,201604049,2020-01-02,2019-11-20 15:30:00,16,Foothill,1622,2,922,CHILD STEALING,unknown,...,CC,UNK,922.0,978.0,NaN,NaN,13700 DESMOND ST,NaN,34.2745,-118.4310
1975814,201604048,2020-01-02,2019-11-20 15:30:00,16,Foothill,1622,2,922,CHILD STEALING,unknown,...,CC,UNK,922.0,978.0,NaN,NaN,13700 DESMOND ST,NaN,34.2745,-118.4310
2030344,191204256,2019-01-05,2019-01-04 23:30:00,12,77th Street,1263,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,IC,Invest Cont,420.0,NaN,NaN,NaN,MANCHESTER,CIMMARON,33.9636,-118.3112
2102344,190616200,2019-07-26,2019-07-26 04:20:00,6,Hollywood,679,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,IC,Invest Cont,420.0,NaN,NaN,NaN,1000 ARDMORE AV,NaN,34.0885,-118.3019
2108045,190408173,2019-04-06,2019-04-06 06:00:00,4,Hollenbeck,453,1,510,VEHICLE - STOLEN,unknown,...,IC,Invest Cont,510.0,NaN,NaN,NaN,PENNSYLVANIA AV,STATE ST,34.0475,-118.2168

In [37]:
la_crimes.loc[la_crimes['Premis Desc'] =='unknown'][['Premis Cd','Premis Desc']]

Empty DataFrame
Columns: [Premis Cd, Premis Desc]
Index: []

In [38]:
#Now we see that many rows have null values for the column Premis Desc

#We replace those null values with unknown

In [39]:
la_crimes.loc[la_crimes['Premis Desc'].isna()]

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
6590,100121447,2010-12-12,2010-12-12 11:50:00,1,Central,185,1,110,CRIMINAL HOMICIDE,unknown,...,AA,Adult Arrest,110.0,NaN,NaN,NaN,200 W OLYMPIC BL,NaN,34.0409,-118.2574
32148,100913648,2010-06-21,2010-06-20 14:35:00,9,Van Nuys,915,1,510,VEHICLE - STOLEN,unknown,...,IC,Invest Cont,510.0,NaN,NaN,NaN,7000 VAN NUYS BL,NaN,34.1976,-118.4487
67340,100816222,2010-09-03,2010-04-16 00:01:00,8,West LA,803,2,813,CHILD ANNOYING (17YRS & UNDER),unknown,...,IC,Invest Cont,813.0,NaN,NaN,NaN,2000 MANDAVILLE C,NaN,34.0949,-118.5111
68276,100818222,2010-11-18,2010-10-16 16:00:00,8,West LA,811,2,812,CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 ...,unknown,...,IC,Invest Cont,812.0,NaN,NaN,NaN,1100 LAS PULGAS RD,NaN,34.0528,-118.5393
71523,100908076,2010-03-16,2010-03-15 22:05:00,15,N Hollywood,1547,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,IC,Invest Cont,420.0,NaN,NaN,NaN,BECK,CHANDLER,34.1687,-118.3834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2109009,190223459,2019-12-17,2019-12-15 21:45:00,2,Rampart,236,2,668,"EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)",0344 1309 1822 0913 1803,...,IC,Invest Cont,668.0,NaN,NaN,NaN,100 S ALVARADO ST,NaN,34.0667,-118.2703
2109581,191515929,2019-08-20,2019-08-20 05:40:00,15,N Hollywood,1599,1,310,BURGLARY,2018 0344 1309 1609 1402 1414 0384,...,IC,Invest Cont,310.0,998.0,NaN,NaN,3700 CAHUENGA BL,NaN,34.1350,-118.3612
2113695,190119416,2019-07-28,2019-07-27 18:00:00,1,Central,157,1,320,"BURGLARY, ATTEMPTED",1607,...,IC,Invest Cont,320.0,NaN,NaN,NaN,600 CROCKER ST,NaN,34.0417,-118.2443
2114205,191221441,2019-08-29,2019-08-29 01:00:00,12,77th Street,1268,1,110,CRIMINAL HOMICIDE,1100 0430 1402 1822 0906,...,AA,Adult Arrest,110.0,998.0,NaN,NaN,8100 S BROADWAY,NaN,33.9660,-118.2783
2114388,190616877,2019-08-07,2019-08-07 03:14:00,6,Hollywood,649,1,310,BURGLARY,1607 0344 1402,...,IC,Invest Cont,310.0,NaN,NaN,NaN,5200 HOLLYWOOD BL,NaN,34.1018,-118.3034

In [40]:
indexes_null_premisdesc = la_crimes.loc[la_crimes ['Premis Desc'].isna()].index
la_crimes.loc[indexes_null_premisdesc,'Premis Desc'] = 'unknown'

In [41]:
la_crimes.loc[la_crimes['Premis Desc']=='unknown'][['Premis Desc','Premis Cd']]

        Premis Desc  Premis Cd
6590        unknown        NaN
32148       unknown        NaN
67340       unknown        NaN
68276       unknown        NaN
71523       unknown        NaN
...             ...        ...
2109009     unknown      418.0
2109581     unknown      256.0
2113695     unknown      256.0
2114205     unknown      256.0
2114388     unknown      418.0

[188 rows x 2 columns]

In [42]:
la_crimes.loc[la_crimes['Premis Desc']=='unknown']['Premis Cd'].unique()

array([ nan, 838., 418., 256.])

In [43]:
cd418 = la_crimes.loc[la_crimes['Premis Cd']==418][['Premis Desc','Premis Cd']]
cd418['Premis Desc'].unique()

array(['unknown'], dtype=object)

In [44]:
cd256 = la_crimes.loc[la_crimes['Premis Cd']== 256][['Premis Desc','Premis Cd']]
cd256['Premis Desc'].unique()

array(['unknown'], dtype=object)

In [45]:
cd838 = la_crimes.loc[la_crimes['Premis Cd']== 838][['Premis Desc','Premis Cd']]
cd838['Premis Desc'].unique()

array(['unknown'], dtype=object)

In [46]:
#We change all the rows with Premis Cd equal to 256,418 or 838, to 0 (unknown)

In [47]:
indexes_wrong_premiscd = la_crimes.loc[(la_crimes ['Premis Cd'] == 256) | 
                                      (la_crimes ['Premis Cd'] == 418) |
                                      (la_crimes ['Premis Cd'] == 838)].index
la_crimes.loc[indexes_wrong_premiscd,'Premis Cd'] = 0

In [48]:
la_crimes['Premis Cd'] = la_crimes['Premis Cd'].fillna(0)

In [49]:
la_crimes['Premis Cd'] = la_crimes['Premis Cd'].astype(int)

In [50]:
#Weapon Used Cd and Weapon Desc columns

In [51]:
la_crimes.loc[la_crimes['Weapon Used Cd'].isna()]

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,2010-02-20,2010-02-20 13:50:00,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,0913 1814 2000,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,2010-09-13,2010-09-12 00:45:00,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329,...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,2010-08-09,2010-08-09 15:15:00,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,0344,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
5,100100506,2010-01-05,2010-01-04 16:50:00,1,Central,162,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0344 1402,...,AA,Adult Arrest,442.0,NaN,NaN,NaN,700 W 7TH ST,NaN,34.0480,-118.2577
6,100100508,2010-01-08,2010-01-07 20:05:00,1,Central,182,1,330,BURGLARY FROM VEHICLE,0344,...,IC,Invest Cont,330.0,NaN,NaN,NaN,PICO BL,GRAND AV,34.0389,-118.2643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2114687,191408297,2019-03-11,2019-03-08 12:00:00,14,Pacific,1438,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0344 1501 1608 1607 0349,...,IC,Invest Cont,440.0,NaN,NaN,NaN,3600 MIDVALE AV,NaN,34.0204,-118.4139
2114691,191307168,2019-02-28,2019-02-28 07:00:00,13,Newton,1394,1,510,VEHICLE - STOLEN,unknown,...,IC,Invest Cont,510.0,NaN,NaN,NaN,100 E 67TH ST,NaN,33.9788,-118.2739
2114695,190715222,2019-08-15,2019-08-14 18:10:00,7,Wilshire,701,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),1300 0344,...,IC,Invest Cont,331.0,NaN,NaN,NaN,WILLOUGHBY AV,ORLANDO AV,34.0871,-118.3732
2114697,191716777,2019-10-17,2019-10-16 18:00:00,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,IC,Invest Cont,420.0,NaN,NaN,NaN,17200 NAPA ST,NaN,34.2266,-118.5085
2114698,190805435,2019-02-01,2019-02-01 16:15:00,8,West LA,852,1,330,BURGLARY FROM VEHICLE,1302 1609 0358 1307 0344 0377 0321,...,IC,Invest Cont,330.0,NaN,NaN,NaN,1700 BARRY AV,NaN,34.0420,-118.4531

In [52]:
indexes_null_weaponcd = la_crimes.loc[la_crimes ['Weapon Used Cd'].isna()].index
la_crimes.loc[indexes_null_weaponcd,'Weapon Used Cd'] = 0

In [53]:
la_crimes.loc[la_crimes['Weapon Desc'].isna()]

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,2010-02-20,2010-02-20 13:50:00,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,0913 1814 2000,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,2010-09-13,2010-09-12 00:45:00,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329,...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,2010-08-09,2010-08-09 15:15:00,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,0344,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
5,100100506,2010-01-05,2010-01-04 16:50:00,1,Central,162,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0344 1402,...,AA,Adult Arrest,442.0,NaN,NaN,NaN,700 W 7TH ST,NaN,34.0480,-118.2577
6,100100508,2010-01-08,2010-01-07 20:05:00,1,Central,182,1,330,BURGLARY FROM VEHICLE,0344,...,IC,Invest Cont,330.0,NaN,NaN,NaN,PICO BL,GRAND AV,34.0389,-118.2643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2114687,191408297,2019-03-11,2019-03-08 12:00:00,14,Pacific,1438,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0344 1501 1608 1607 0349,...,IC,Invest Cont,440.0,NaN,NaN,NaN,3600 MIDVALE AV,NaN,34.0204,-118.4139
2114691,191307168,2019-02-28,2019-02-28 07:00:00,13,Newton,1394,1,510,VEHICLE - STOLEN,unknown,...,IC,Invest Cont,510.0,NaN,NaN,NaN,100 E 67TH ST,NaN,33.9788,-118.2739
2114695,190715222,2019-08-15,2019-08-14 18:10:00,7,Wilshire,701,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),1300 0344,...,IC,Invest Cont,331.0,NaN,NaN,NaN,WILLOUGHBY AV,ORLANDO AV,34.0871,-118.3732
2114697,191716777,2019-10-17,2019-10-16 18:00:00,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,IC,Invest Cont,420.0,NaN,NaN,NaN,17200 NAPA ST,NaN,34.2266,-118.5085
2114698,190805435,2019-02-01,2019-02-01 16:15:00,8,West LA,852,1,330,BURGLARY FROM VEHICLE,1302 1609 0358 1307 0344 0377 0321,...,IC,Invest Cont,330.0,NaN,NaN,NaN,1700 BARRY AV,NaN,34.0420,-118.4531

In [54]:
indexes_null_weapondesc = la_crimes.loc[la_crimes ['Weapon Desc'].isna()].index
la_crimes.loc[indexes_null_weapondesc,'Weapon Desc'] = 'unknown'

In [55]:
 la_crimes['Weapon Used Cd'] = la_crimes['Weapon Used Cd'].astype(int)

In [56]:
#Status and Status Desc columns

In [57]:
#Now we check the status of the crime incident
#We see that the columns Status and Status Desc have some differences.

In [58]:
la_crimes['Status'].value_counts()

IC    1623829
AO     250589
AA     219081
JA      15864
JO       5301
CC         29
TH          1
13          1
19          1
Name: Status, dtype: int64

In [59]:
la_crimes['Status Desc'].value_counts()

Invest Cont     1623829
Adult Other      250589
Adult Arrest     219081
Juv Arrest        15864
Juv Other          5301
UNK                  35
Name: Status Desc, dtype: int64

In [60]:
la_crimes.loc[la_crimes['Status Desc'] == 'UNK']

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
100040,101208618,2010-03-02,2010-03-02 03:30:00,12,77th Street,1248,1,210,ROBBERY,0305 0342 0344 0416 1008,...,NaN,UNK,210.0,NaN,NaN,NaN,70TH ST,MENLO,33.9764,-118.2892
151803,101700682,2010-03-09,2010-03-08 11:55:00,17,Devonshire,1764,2,653,"CREDIT CARDS, FRAUD USE ($950.01 & OVER)",0377 0930 1402 1822,...,CC,UNK,653.0,998.0,NaN,NaN,19300 NORDHOFF ST,NaN,34.2355,-118.5536
160732,101721148,2010-11-15,2010-11-14 17:00:00,17,Devonshire,1756,2,900,VIOLATION OF COURT ORDER,1501,...,CC,UNK,900.0,NaN,NaN,NaN,17800 LASSEN ST,NaN,34.2504,-118.5216
219776,112109831,2011-04-29,2011-04-28 22:00:00,21,Topanga,2139,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),0344 1202,...,CC,UNK,331.0,NaN,NaN,NaN,7300 CORBIN AV,NaN,34.2031,-118.5623
285526,111204921,2011-01-14,2011-01-12 18:30:00,12,77th Street,1266,1,210,ROBBERY,0202 0305 0344 0370 0416 0429 0906 1251 1259 1822,...,CC,UNK,210.0,NaN,NaN,NaN,HOOVER ST,83RD ST,33.9632,-118.2871
400260,111225404,2011-10-26,2011-10-26 07:20:00,12,77th Street,1243,2,920,KIDNAPPING - GRAND ATTEMPT,0305 1251 1258 1313 1822,...,CC,UNK,920.0,NaN,NaN,NaN,68TH ST,VAN NESS,33.9790,-118.3112
485891,141215426,2014-06-30,2012-01-01 12:00:00,12,77th Street,1268,2,354,THEFT OF IDENTITY,0100 1822 0917,...,CC,UNK,354.0,NaN,NaN,NaN,200 E 85TH ST,NaN,33.9610,-118.2717
563146,120619583,2012-07-16,2012-06-16 12:00:00,6,Hollywood,644,2,922,CHILD STEALING,unknown,...,CC,UNK,922.0,986.0,NaN,NaN,1300 N VISTA ST,NaN,34.0944,-118.3517
598768,120123632,2012-11-17,2012-11-16 20:30:00,1,Central,192,2,888,TRESPASSING,0601 1609 0329,...,TH,UNK,888.0,NaN,NaN,NaN,400 W VENICE BL,NaN,34.0365,-118.2676
631373,131411831,2013-04-26,2013-04-02 23:00:00,14,Pacific,1494,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0344,...,CC,UNK,440.0,NaN,NaN,NaN,00 WORLD WY,NaN,33.9454,-118.3998
633764,131718469,2013-11-09,2013-11-09 18:30:00,17,Devonshire,1718,1,310,BURGLARY,0344 1606,...,CC,UNK,310.0,NaN,NaN,NaN,11400 GAYNOR AV,NaN,34.2775,-118.4807
722953,131418620,2013-07-19,2013-07-19 19:40:00,14,Pacific,1441,1,210,ROBBERY,0344 0416,...,CC,UNK,210.0,NaN,NaN,NaN,OCEAN FRONT WK,MARKET ST,33.9875,-118.4741
755801,130510483,2013-05-26,2013-05-25 20:00:00,5,Harbor,507,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0344,...,NaN,UNK,440.0,NaN,NaN,NaN,1300 W SEPULVEDA BL,NaN,33.8135,-118.2992
823129,141225513,2014-11-26,2014-11-26 11:00:00,12,77th Street,1241,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 0352 0913,...,CC,UNK,341.0,NaN,NaN,NaN,6500 S VICTORIA AV,NaN,33.9806,-118.3323
830482,140606335,2014-02-12,2014-02-12 00:30:00,6,Hollywood,632,1,310,BURGLARY,0344,...,CC,UNK,310.0,NaN,NaN,NaN,8600 FRANKLIN AV,NaN,34.1010,-118.3776
841106,141308108,2014-03-16,2014-03-16 15:30:00,13,Newton,1347,1,510,VEHICLE - STOLEN,unknown,...,13,UNK,510.0,NaN,NaN,NaN,ALAMEDA ST,VERNON AV,34.0039,-118.2392
847932,140105268,2014-01-18,2014-01-18 09:30:00,1,Central,157,1,310,BURGLARY,1607 0344,...,CC,UNK,310.0,NaN,NaN,NaN,700 E 6TH ST,NaN,34.0412,-118.2436
854169,141218155,2014-08-09,2014-07-30 12:00:00,12,77th Street,1251,2,664,"BUNCO, PETTY THEFT",0701 0800 0344 0923 0913,...,CC,UNK,664.0,NaN,NaN,NaN,7700 CRENSHAW BL,NaN,33.9700,-118.3308
860348,140308003,2014-03-13,2014-03-11 20:00:00,3,Southwest,308,1,330,BURGLARY FROM VEHICLE,0344 1300,...,CC,UNK,330.0,NaN,NaN,NaN,900 W 23RD ST,NaN,34.0334,-118.2799
931959,141223962,2014-10-31,2014-10-30 15:00:00,12,77th Street,1239,2,920,KIDNAPPING - GRAND ATTEMPT,0342 1309 1808 1313 0448,...,CC,UNK,920.0,NaN,NaN,NaN,1000 W 58TH PL,NaN,33.9884,-118.2915
973320,141314455,2014-07-12,2014-07-11 02:00:00,13,Newton,1352,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0344 1221 0352,...,CC,UNK,440.0,NaN,NaN,NaN,100 E 45TH ST,NaN,34.0029,-118.2740
1011274,151224700,2015-10-29,2015-10-28 12:00:00,12,77th Street,1267,1,210,ROBBERY,1309 1202 1822 0344 0346,...,CC,UNK,210.0,NaN,NaN,NaN,MANCHESTER AV,FIGUEROA,33.9601,-118.2827
1058874,151216330,2015-06-30,2015-06-26 21:30:00,12,77th Street,1243,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1309 0342 0334 0411,...,CC,UNK,230.0,NaN,NaN,NaN,67TH ST,WESTERN AV,33.9785,-118.3090
1115808,151316498,2015-08-17,2015-08-14 15:00:00,13,Newton,1367,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1602,...,CC,UNK,740.0,NaN,NaN,NaN,5100 HOLMES AV,NaN,33.9962,-118.2411
1254665,160217814,2016-09-27,2016-09-26 16:45:00,2,Rampart,247,2,664,"BUNCO, PETTY THEFT",0344 0342 0800 1251,...,CC,UNK,664.0,NaN,NaN,NaN,1800 MARYLAND ST,NaN,34.0596,-118.2700
1279006,160327645,2016-12-20,2016-12-20 13:50:00,3,Southwest,361,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0325 0378,...,CC,UNK,442.0,NaN,NaN,NaN,5000 RODEO RD,NaN,34.0215,-118.3524
1359864,161922607,2016-11-30,2016-11-25 09:50:00,19,Mission,1912,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,19,UNK,420.0,NaN,NaN,NaN,15800 OLDEN ST,NaN,34.3146,-118.4752
1510762,170314115,2017-06-01,2017-06-01 00:30:00,3,Southwest,337,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 1402,...,CC,UNK,740.0,NaN,NaN,NaN,3100 RAYMOND AV,NaN,34.0268,-118.2981
1625775,171221278,2017-08-25,2017-07-29 14:00:00,12,77th Street,1245,1,440,THEFT PLAIN - PETTY ($950 & UNDER),1251 0344,...,CC,UNK,440.0,NaN,NaN,NaN,6500 S NORMANDIE AV,NaN,33.9806,-118.3003
1871854,181105575,2018-02-06,2018-02-05 17:20:00,11,Northeast,1183,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0344 2004,...,CC,UNK,745.0,NaN,NaN,NaN,1400 ECHO PARK AV,NaN,34.0832,-118.2572
1947458,191307542,2019-03-06,2019-03-06 16:45:00,13,Newton,1307,1,510,VEHICLE - STOLEN,unknown,...,NaN,UNK,510.0,NaN,NaN,NaN,STANFORD,8TH ST,34.0365,-118.2468
1959362,192117351,2019-10-12,2019-10-12 17:00:00,21,Topanga,2145,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0344,...,CC,UNK,440.0,NaN,NaN,NaN,6900 TOPANGA CANYON BL,NaN,34.1923,-118.6104
1968622,201604049,2020-01-02,2019-11-20 15:30:00,16,Foothill,1622,2,922,CHILD STEALING,unknown,...,CC,UNK,922.0,978.0,NaN,NaN,13700 DESMOND ST,NaN,34.2745,-118.4310
1973869,191421123,2019-09-29,2019-09-28 23:30:00,14,Pacific,1464,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 1608,...,CC,UNK,341.0,NaN,NaN,NaN,5800 SEAWALK DR,NaN,33.9724,-118.4264
1975814,201604048,2020-01-02,2019-11-20 15:30:00,16,Foothill,1622,2,922,CHILD STEALING,unknown,...,CC,UNK,922.0,978.0,NaN,NaN,13700 DESMOND ST,NaN,34.2745,-118.4310

In [61]:
indexes_status = la_crimes.loc[(la_crimes['Status'] == '19')|
                              (la_crimes['Status'] == '13') | (la_crimes['Status'] == 'TH')|
                               (la_crimes['Status'].isna())
                              ]['Status'].index #finding the indexes of nan Status or status 19,13,TH
la_crimes.loc[indexes_status,'Status'] = 'CC'

In [62]:
indexes_status_desc = la_crimes.loc[la_crimes['Status Desc'].isna()]['Status'].index #finding the indexes of nan Status or status 19,13,TH
la_crimes.loc[indexes_status_desc,'Status Desc'] = 'UNK'

In [63]:
#Crm Cd columns

In [64]:
indexes_crm1null = la_crimes.loc[(la_crimes ['Crm Cd 1'].isna()) ].index
la_crimes.loc[indexes_crm1null,:]

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
55532,100707214,2010-03-14,2010-03-13 02:30:00,7,Wilshire,767,2,624,BATTERY - SIMPLE ASSAULT,0344 0400 0416 1300,...,IC,Invest Cont,NaN,624.0,NaN,NaN,PICO BL,NORTON AV,34.0476,-118.3239
288235,110310134,2011-04-08,2011-03-26 08:00:00,3,Southwest,312,2,942,BRIBERY,1300 1402,...,IC,Invest Cont,NaN,942.0,99.0,NaN,5100 ROSELAND ST,NaN,34.0274,-118.3542
358506,110811926,2011-07-01,2011-07-01 20:11:00,8,West LA,835,1,210,ROBBERY,unknown,...,IC,Invest Cont,NaN,210.0,NaN,NaN,11000 SANTA MONICA BL,NaN,34.0484,-118.4411
507665,120325216,2012-11-19,2012-11-19 19:30:00,3,Southwest,329,1,440,THEFT PLAIN - PETTY ($950 & UNDER),0344,...,IC,Invest Cont,NaN,440.0,NaN,NaN,500 W 27TH ST,NaN,34.0268,-118.2753
1176227,150318476,2015-08-17,2015-08-16 12:00:00,3,Southwest,363,1,761,BRANDISH WEAPON,0913 0906 0334 0421 0319 0444 0432 1816,...,AO,Adult Other,NaN,761.0,93.0,NaN,4100 PALMWOOD DR,NaN,34.0137,-118.3435
1188315,150517852,2015-11-09,2015-10-09 18:00:00,5,Harbor,529,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),0344 1300 1606 0321,...,IC,Invest Cont,NaN,420.0,NaN,NaN,200 BERTH,NaN,33.7753,-118.2456
1697697,181824031,2018-12-13,2018-12-13 19:40:00,18,Southeast,1842,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0906 0450 1402,...,IC,Invest Cont,NaN,230.0,NaN,NaN,400 W 109TH ST,NaN,33.9374,-118.2805
1875523,181117551,2018-10-05,2018-10-05 09:00:00,11,Northeast,1162,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0445 0432 1822 0443 1266,...,AA,Adult Arrest,NaN,230.0,93.0,NaN,1300 N VERMONT AV,NaN,34.0956,-118.2918
1977968,191400827,2019-07-20,2019-07-20 09:45:00,14,Pacific,1463,2,888,TRESPASSING,1501,...,IC,Invest Cont,NaN,888.0,NaN,NaN,5300 ALLA RD,NaN,33.9779,-118.4264
2080625,190308122,2019-03-05,2019-03-05 21:30:00,3,Southwest,395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER),0216 0344 1606 1822 1300,...,IC,Invest Cont,NaN,331.0,NaN,NaN,39TH ST,NORMANDIE AV,34.0073,-118.3108

In [65]:
la_crimes.loc[indexes_crm1null,'Crm Cd 1'] = la_crimes.loc[indexes_crm1null,'Crm Cd 2']
la_crimes.loc[indexes_crm1null,'Crm Cd 2'] = la_crimes.loc[indexes_crm1null,'Crm Cd 3']
la_crimes.loc[indexes_crm1null,'Crm Cd 3'] = la_crimes.loc[indexes_crm1null,'Crm Cd 4']

In [66]:
la_crimes ['Crm Cd 2'] = la_crimes ['Crm Cd 2'].fillna(-1)
la_crimes ['Crm Cd 3'] = la_crimes ['Crm Cd 3'].fillna(-1)
la_crimes ['Crm Cd 4'] = la_crimes ['Crm Cd 4'].fillna(-1)

In [67]:
la_crimes['Crm Cd 1'] = la_crimes['Crm Cd 1'].astype(int)
la_crimes['Crm Cd 2'] = la_crimes['Crm Cd 2'].astype(int)
la_crimes['Crm Cd 3'] = la_crimes['Crm Cd 3'].astype(int)
la_crimes['Crm Cd 4'] = la_crimes['Crm Cd 4'].astype(int)

In [68]:
indexes_crm_crm2 = la_crimes.loc[la_crimes ['Crm Cd'] ==  la_crimes ['Crm Cd 2']].index
la_crimes.loc[indexes_crm_crm2,'Crm Cd 2'] = la_crimes.loc[indexes_crm_crm2,'Crm Cd 1'].copy()
la_crimes.loc[indexes_crm_crm2,'Crm Cd 1'] = la_crimes.loc[indexes_crm_crm2,'Crm Cd'].copy()

In [69]:
indexes_crm_crm3 = la_crimes.loc[la_crimes ['Crm Cd'] ==  la_crimes ['Crm Cd 3']].index
la_crimes.loc[indexes_crm_crm3,'Crm Cd 3'] = la_crimes.loc[indexes_crm_crm3,'Crm Cd 1'].copy()
la_crimes.loc[indexes_crm_crm3,'Crm Cd 1'] = la_crimes.loc[indexes_crm_crm3,'Crm Cd'].copy()

In [70]:
la_crimes.loc[la_crimes ['Crm Cd'] ==  la_crimes ['Crm Cd 4']].index

Int64Index([], dtype='int64')

In [71]:
la_crimes = la_crimes.drop(['Crm Cd 1'], axis=1)

In [72]:
#LOCATION Column

In [73]:
#Some locations have a bunch of white spaces in between their words

In [74]:
la_crimes ['LOCATION'].value_counts()

6TH                          ST            4756
7TH                          ST            3774
9300    TAMPA                        AV    3658
6TH                                        3235
6600    TOPANGA CANYON               BL    3064
                                           ...
5800    FARRALONE                    AV       1
CUMBRE                                        1
FAIRBURN                                      1
MATEO                        PL               1
4500    ALAMEDA                               1
Name: LOCATION, Length: 75251, dtype: int64

In [75]:
la_crimes['LOCATION'] = la_crimes['LOCATION'].str.replace(' +', ' ').str.strip()

C:\Users\Asus\AppData\Local\Temp\ipykernel_2788\3917435660.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  la_crimes['LOCATION'] = la_crimes['LOCATION'].str.replace(' +', ' ').str.strip()

In [76]:
#Cross Street column

In [77]:
indexes_null_cross = la_crimes.loc[la_crimes ['Cross Street'].isna()].index
la_crimes.loc[indexes_null_cross,'Cross Street'] = 'unknown'

In [78]:
la_crimes['Cross Street'].value_counts()

unknown                            1759334
BROADWAY                              6157
FIGUEROA                              3801
VERMONT                      AV       3746
SAN PEDRO                             3659
                                    ...
QUARTERDECK                  AV          1
INDUSTRY                                 1
W C FIELDS                   DR          1
NORDICA                                  1
EDGEWATER                    AV          1
Name: Cross Street, Length: 12869, dtype: int64

In [79]:
la_crimes['Cross Street'] = la_crimes['Cross Street'].str.replace(' +', ' ').str.strip()

C:\Users\Asus\AppData\Local\Temp\ipykernel_2788\3613288552.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  la_crimes['Cross Street'] = la_crimes['Cross Street'].str.replace(' +', ' ').str.strip()

In [80]:
la_crimes.loc[la_crimes['Cross Street'] == 'unknown']

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Weapon Desc,Status,Status Desc,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,2010-02-20,2010-02-20 13:50:00,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,0913 1814 2000,...,unknown,AA,Adult Arrest,-1,-1,-1,300 E GAGE AV,unknown,33.9825,-118.2695
2,70309629,2010-08-09,2010-08-09 15:15:00,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,0344,...,unknown,IC,Invest Cont,-1,-1,-1,1300 E 21ST ST,unknown,34.0224,-118.2524
5,100100506,2010-01-05,2010-01-04 16:50:00,1,Central,162,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),0344 1402,...,unknown,AA,Adult Arrest,-1,-1,-1,700 W 7TH ST,unknown,34.0480,-118.2577
7,100100509,2010-01-09,2010-01-08 21:00:00,1,Central,157,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0416,...,UNKNOWN WEAPON/OTHER WEAPON,AA,Adult Arrest,-1,-1,-1,500 CROCKER ST,unknown,34.0435,-118.2427
8,100100510,2010-01-09,2010-01-09 02:30:00,1,Central,171,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0400 0416,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,-1,-1,-1,800 W OLYMPIC BL,unknown,34.0450,-118.2640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2114692,190906699,2019-02-24,2019-02-23 22:20:00,9,Van Nuys,904,1,210,ROBBERY,0344 0302 0334 0355 1310 1420 1822 0354,...,OTHER FIREARM,IC,Invest Cont,998,-1,-1,7600 WILLIS AV,unknown,34.2085,-118.4553
2114693,190506304,2019-02-22,2019-02-22 08:40:00,5,Harbor,569,2,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,0443 0419 0416 1259,...,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,-1,-1,-1,100 W 22ND ST,unknown,33.7257,-118.2801
2114694,190608903,2019-03-28,2019-03-28 04:00:00,6,Hollywood,644,1,648,ARSON,0601 1501,...,FIRE,IC,Invest Cont,-1,-1,-1,1400 N LA BREA AV,unknown,34.0962,-118.3490
2114697,191716777,2019-10-17,2019-10-16 18:00:00,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,unknown,IC,Invest Cont,-1,-1,-1,17200 NAPA ST,unknown,34.2266,-118.5085
2114698,190805435,2019-02-01,2019-02-01 16:15:00,8,West LA,852,1,330,BURGLARY FROM VEHICLE,1302 1609 0358 1307 0344 0377 0321,...,unknown,IC,Invest Cont,-1,-1,-1,1700 BARRY AV,unknown,34.0420,-118.4531

In [81]:
la_crimes = la_crimes.drop(['Cross Street'], axis=1)

In [82]:
#LONGTITUDE-LATITUDE

In [83]:
#We see that some crimes have values for longtitude and latitude equal to 
#Those values are considered missing because they correspond to the Gulf of Guinea.

In [84]:
la_crimes.loc[(la_crimes['LON'] == 0) & (la_crimes['LAT'] == 0) ]

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,LAT,LON
49703,100618355,2010-07-14,2010-07-12 19:00:00,6,Hollywood,665,1,330,BURGLARY FROM VEHICLE,0344 1300 1302,...,0,unknown,IC,Invest Cont,-1,-1,-1,900 N CISTRUS AV,0.0,0.0
49800,100618603,2010-07-19,2010-07-19 23:45:00,6,Hollywood,665,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",0329 0906,...,0,unknown,AA,Adult Arrest,998,-1,-1,6300 WILLOUGBY,0.0,0.0
60848,100718479,2010-11-29,2010-11-29 16:30:00,7,Wilshire,709,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0416 1402,...,122,HECKLER & KOCH 93 SEMIAUTOMATIC ASSAULT RIFLE,IC,Invest Cont,998,-1,-1,HARBOR,0.0,0.0
84978,101016365,2010-09-09,2010-08-23 15:00:00,10,West Valley,1000,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,0416 2000,...,0,unknown,IC,Invest Cont,-1,-1,-1,CITY OF WINNETKA,0.0,0.0
123985,101409719,2010-04-01,2010-03-30 21:00:00,14,Pacific,1412,1,510,VEHICLE - STOLEN,unknown,...,0,unknown,IC,Invest Cont,-1,-1,-1,WINDWARD AV,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1982414,191915311,2019-08-22,2019-08-21 11:00:00,19,Mission,1900,1,236,INTIMATE PARTNER - AGGRAVATED ASSAULT,0400 0448 2000 0913,...,400,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,Adult Arrest,-1,-1,-1,UNKNOWN,0.0,0.0
1995724,191409480,2019-03-31,2019-03-31 03:00:00,14,Pacific,1400,2,624,BATTERY - SIMPLE ASSAULT,0400 0416,...,400,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,-1,-1,-1,96TH,0.0,0.0
2013881,190918499,2019-10-18,2019-10-15 16:30:00,9,Van Nuys,936,2,626,INTIMATE PARTNER - SIMPLE ASSAULT,1814 2000 0448,...,400,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AA,Adult Arrest,-1,-1,-1,13600 LANAY ST,0.0,0.0
2022655,191719423,2019-12-15,2019-12-13 11:00:00,17,Devonshire,1786,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),unknown,...,0,unknown,IC,Invest Cont,-1,-1,-1,BALBOA BL,0.0,0.0
2078950,200114120,2020-06-29,2019-12-28 16:20:00,1,Central,162,2,354,THEFT OF IDENTITY,1501,...,0,unknown,IC,Invest Cont,-1,-1,-1,800 S FLOWER ST,0.0,0.0

In [85]:
#SAVING THE CLEANED DATASET

In [86]:
la_crimes.to_csv('LA Crime_Cleared.csv', index=False)